version: '3'
services:

    nginx:
        container_name: nginx
        image: nginx:1.17
        restart: always
        ports:
            - "9999:80"
        volumes:
            - ../:/var/www
            - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
        links:
            - php
    php:
        container_name: php
        build:
            context: .
            dockerfile: Dockerfile
        restart: always
        volumes:
            - ../:/var/www
            - ./php-config/php.ini:/usr/local/etc/php/php.ini

    composer:
        container_name: composer
        image: composer:1.9.0
        command: tail -f /dev/null
        volumes:
            - ../:/var/www

    mysql:
        container_name: mysql
        image: mysql:5.7
        command: mysqld --max-allowed-packet=64M --character-set-server=utf8 --collation-server=utf8_unicode_ci --init-connect='SET NAMES UTF8;' --innodb-flush-log-at-trx-commit=0
        volumes:
            - ~/storage/mysql/data:/var/lib/mysql

        environment:
            - "MYSQL_ROOT_PASSWORD=LSJW89KSLlsw8wj8SLJS"
            - "MYSQL_DATABASE=notes"
            - "MYSQL_USER=ikram"
            - "MYSQL_PASSWORD=ikram456"
        ports:
            - "3306:3306"

    phpmyadmin:
        container_name: phpmyadmin
        image: phpmyadmin/phpmyadmin
        restart: always
        environment:
            - PMA_HOST=mysql
            - PMA_PORT=3306
        ports:
            - 8000:80
        volumes:
            - /sessions